name: Compilar Instalador Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      # Definimos las variables a nivel global para asegurar que el proceso las lea
      OPENSSL_DIR: C:\vcpkg\installed\x64-windows-static-md
      OPENSSL_NO_VENDOR: 1
      VCPKG_ROOT: C:\vcpkg

    steps:
      - name: Clonar código fuente
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Instalar OpenSSL (vcpkg)
        run: |
          vcpkg install openssl:x64-windows-static-md

      - name: Instalar dependencias del frontend
        run: npm install

      - name: Construir y Empaquetar Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'App - Versión ${{ github.ref_name }}'
          releaseBody: 'Instalador ejecutable (.exe) para Windows.'
          releaseDraft: false
          prerelease: false
          args: --target x86_64-pc-windows-msvc
